### ISSUE TITLE
Unable to install multiplot in ROS Kinetic

### ISSUE THREAD

**Issue by Rangeesh** [ANYbotics/rqt_multiplot_plugin#32]
While executing the following command in the terminal - `sudo apt-get install ros-kinetic-rqt-multiplot` I get the following error:

`Err:1 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-variant-msgs amd64 0.1.5-0xenial-20181128-003748-0800
  404  Not Found [IP: 64.50.236.52 80]
Err:2 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-variant-topic-tools amd64 0.1.5-0xenial-20190320-124933-0800
  404  Not Found [IP: 64.50.236.52 80]
Err:3 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-rqt-multiplot amd64 0.0.10-0xenial-20190320-141655-0800
  404  Not Found [IP: 64.50.236.52 80]
E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-variant-msgs/ros-kinetic-variant-msgs_0.1.5-0xenial-20181128-003748-0800_amd64.deb  404  Not Found [IP: 64.50.236.52 80]

E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-variant-topic-tools/ros-kinetic-variant-topic-tools_0.1.5-0xenial-20190320-124933-0800_amd64.deb  404  Not Found [IP: 64.50.236.52 80]

E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-rqt-multiplot/ros-kinetic-rqt-multiplot_0.0.10-0xenial-20190320-141655-0800_amd64.deb  404  Not Found [IP: 64.50.236.52 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

How do I solve this?

**Comment by samuelba** [comment]
As you can see here 
http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-rqt-multiplot/ 
http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-variant-msgs/
http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-variant-topic-tools/
the packages are on the ROS Debian Package Repository. A guess this was a problem with the ROS server.
