### ISSUE TITLE
Load perspective file from network drive

### ISSUE THREAD

**Issue by Ishadijcks** [ANYbotics/rqt_multiplot_plugin#33]
For our project we use rqt_multiplot on multiple machines connected to the same robot.
It would be great if we could load perspective files from a network drive so all developers have access to the same perspectives instead of everyone having local copies.

**Comment by remod** [comment]
Wouldn't using git or any other version control software solve this issue?

**Comment by Ishadijcks** [comment]
Oh wow, that does indeed make much more sense. Now idea what I was thinking :)

Thanks!
